global using AutoFixture;
global using AutoMapper;
global using FluentAssertions;
global using FluentValidation;
global using Microsoft.AspNetCore.Mvc;
global using MongoDB.Bson;
global using Moq;
global using Notes.Application.Common;
global using Xunit;
